### ISSUE TITLE
Inconsistent action error for molecule

### ISSUE THREAD

**Issue by haonan3** [john-bradshaw/electro#1]
When I run the code, the following error occurred.

rxn_steps.data.lef_consistency_errors.InconsistentActionError: Inconsistent action error for molecule: ['[CH2:1]([c:2]1[cH:3][cH:4][cH:5][cH:6][cH:7]1)[P:8]([OH:9])([OH:10])=[O:11].[cH:12]1[cH:13][c:14]2[cH:15][c:16]3[cH:17][cH:18][c:19]([cH:20][c:21]4[cH:22][cH:23][c:24]([cH:25][c:26]5[cH:27][cH:28][c:29]([cH:30][c:31]1[n:32]2)[nH:33]5)[n:34]4)[nH:35]3', '[CH2:36][CH3:37].[Cl:38][CH:39]([Cl:40])[Cl:41]', '[cH:12]1[cH:13][c:14]2[cH:15][c:16]3[cH:17][cH:18][c:19]([cH:20][c:21]4[cH:22][cH:23][c:24]([cH:25][c:26]5[cH:27][cH:28][c:29]([cH:30][c:31]1[nH:32]2)[n:33]5)[nH:34]4)[n:35]3.[CH2:1]([c:2]1[cH:3][cH:4][cH:5][cH:6][cH:7]1)[P:8](=[O:9])([OH:10])[OH:11]', '[9, 9, 8, 11]']

In transforms.py file, the error arised when checking `is_sub_mol_consistent_with_super(product_mol, intermediates[-1])`.

Should I just skip that reaction?

**Comment by junsu-kim97** [comment]
@haonan3 did you solve this error?

**Comment by haonan3** [comment]
Yes, thanks for your reply. I have closed this issue comment.
